import "./globals.css";
import Navbar from "./components/Navbar";
import { Concert_One } from "next/font/google";
import SessionWrapper from "./components/SessionWrapper";
import Footer from "./components/Footer";


const font = Concert_One({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <SessionWrapper>
      <body className={font.className}>
        <header>
          <Navbar />
        </header>
        <main>{children}</main>
       <Footer></Footer>
      </body>
      </SessionWrapper>
    </html>
  );
}
